# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
               result=$(curl -v -X POST https://elastic.snaplogic.com/api/1/rest/public/assetapi/project/Partners/Infosys/Alok_Test03'$(Build.BuildNumber)' \
                  -u  alok.tiwari@infosys.com:Snapkapass@99 \
                  -H "content-type:application/json" \
                  -d '{"permissions":[{"perms":["R","W","X"],"inherit":true,"subject_type":"USER","subject":"alok.tiwari@infosys.com"}]}' \
                  --trace-ascii /dev/stdout)
  displayName: 'Creating the Project Space'
- script: |
               result=$(curl -X POST https://elastic.snaplogic.com/api/1/rest/public/project/checkout/Partners/Infosys/Alok_Test03'$(Build.BuildNumber)' \
                  -u  alok.tiwari@infosys.com:Snapkapass@99 \
                  -H "content-type:application/json" \
                  -d '{"repo":"$REPO","ref":"$BRANCH"}' \
                  --trace-ascii /dev/stdout)
  displayName: 'Clone to Test project'
  
