# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
name: CICD_$(Date:yyyyMMdd)_$(Rev:r)

jobs:
- job: Test
  condition: startsWith(variables['Buid.SourceBranch'], 'refs/heads/main/')
  displayName: Build Test Project and Run Tests
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
                export result=$(curl -v -X POST https://elastic.snaplogic.com/api/1/rest/public/assetapi/project/Partners/Infosys/Alok_Test03'$(Build.BuildNumber)' \
                    -u  alok.tiwari@infosys.com:Snapkapass@99 \
                    -H "content-type:application/json" \
                    -d '{"permissions":[{"perms":["R","W","X"],"inherit":true,"subject_type":"USER","subject":"alok.tiwari@infosys.com"}]}' \
                    --trace-ascii /dev/stdout)
                    echo "##vso[task.setvariable variable=RESULT]$RESULT"
    displayName: 'Creating the Project Space or Project'
  - script: |
                export result=$(curl -X POST https://elastic.snaplogic.com/api/1/rest/public/project/checkout/Partners/Infosys/Alok_Test03'$(Build.BuildNumber)' \
                    -u  alok.tiwari@infosys.com:Snapkapass@99 \
                    -H "content-type:application/json" \
                    -d '{"repo":"alok5522/SnaplogicT","ref":"main","hard_reset":true,"discard_untracked_file":true}' \
                    --trace-ascii /dev/stdout)
                    echo "##vso[task.setvariable variable=RESULT]$RESULT"
    displayName: 'Clone to Test project'
    
